### ISSUE TITLE
Actor nicknames don't show when in F1

### ISSUE THREAD

**Issue by ImGRUI** [lumaa-dev/Act#1]
When I go to F1, actor nicknames don't render. Is this a bug or not?

**Comment by lumaa-dev** [comment]
No this is not a bug, this is a default Minecraft feature. I guess I could change it somehow and make it toggleable if you want.

**Comment by lumaa-dev** [comment]
I tried looking for the Minecraft code to maybe disable this feature from the game, it seems that it's well hidden.
