### ISSUE TITLE
mod not working

### ISSUE THREAD

**Issue by Saiko125** [lumaa-dev/Act#2]
hello I have slight problem using the mod 

whenever I type command /actor "ign" ["ign" being nickname of existing or not existing player]
it displays the error 
![image](https://github.com/V-Fast/Act/assets/86660217/34ece89a-15b8-45b5-856b-4b45d65bb143)

is there any way to fix it?

**Comment by lumaa-dev** [comment]
Closing because no updates where given since, although mentioned 
(Latest updates on Discord)
